<a href="https://colab.research.google.com/github/sungwanjoe87/home/blob/main/11.deep/d0714/02_%EB%94%A5%EB%9F%AC%EB%8B%9D_mnist.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Keras 딥러닝 - mnist

In [142]:
import sklearn
from sklearn.linear_model import SGDClassifier
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib
from sklearn.model_selection import train_test_split
matplotlib.rcParams['font.family'] = 'Malgun Gothic'
matplotlib.rcParams['axes.unicode_minus'] = False
from tensorflow import keras

In [143]:
## 데이터 불러오기
(train_data,train_label),(test_data,test_label) = keras.datasets.fashion_mnist.load_data()

In [144]:
## 데이터전처리

#1.데이터 확인. - pandas 는 info, describe 로 확인.
train_data.shape #(60000, 28, 28)


(60000, 28, 28)

In [145]:
train_label.shape #(60000,)

(60000,)

In [146]:
# 2. class 확인. 클래스 당 데이터 숫자 확인. pandas는 특성 컬럼확인. 클래스 컬럼 확인.
np.unique(train_label, return_counts=True)

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=uint8),
 array([6000, 6000, 6000, 6000, 6000, 6000, 6000, 6000, 6000, 6000]))

In [147]:
## 정규화/표준화
train_scaled = train_data/255.0
test_scaled = test_data/255.0


In [148]:
# train_scaled  = train_scaled.reshape(-1,28*28)
# test_scaled  = test_scaled.reshape(-1,28*28)


In [149]:
## 검증데이터 나누기
# train_data, test_data, val,data
sub_data,val_data,sub_label,val_label = train_test_split(train_scaled,train_label)

In [150]:
## 클래스 개수 - 10개
np.unique(train_label)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=uint8)

In [151]:
## 1.딥러닝 선언 (셋중 하나만)
## keras 출력층 = 클래스 갯수와 같아야 함
## 클래스 다중 : activation='softmax', 이진 : sigmoid
## 출력층
# dense1 = keras.layers.Dense(100, activation='relu',input_shape=(28,28))
# dense2 = keras.layers.Dense(10, activation='softmax')
# ## 알고리즘 선택.
# model = keras.Sequential(dense1,dense2)
# ## 설정. 이진분류에서는 - sparse_binary_crossentropy / accuracy : 정확도 출력. sparse_ : 라벨에 대한 원핫인코딩
# model.compile(loss='sparse_categorical_crossentropy',metrics='accuracy')

In [152]:
## 2.딥러닝 선언. (셋중 하나만)
# model = keras.Sequential([
#                          keras.layers.Dense(100,activation='relu',input_shape=(784,)),
#                          keras.layers.Dense(10,activation='softmax')
# ])

# model.compile(loss='sparse_categorical_crossentropy',metrics='accuracy')

In [153]:
## 3.딥러닝 선언. (셋중 하나만) ## 권장.
model = keras.Sequential()
# model.add(keras.layers.Dense(100,activation='relu',input_shape=(784,)))
model.add(keras.layers.Flatten(input_shape=(28,28)))
model.add(keras.layers.Dense(100,activation='relu'))
model.add(keras.layers.Dense(10,activation='softmax',name='LAST_DENSE')) ## 마지막 층은 클래스 숫자와 같이.
model.compile(loss='sparse_categorical_crossentropy',metrics='accuracy')

In [154]:
## 훈련 - 2차원데이터
model.fit(train_scaled,train_label,epochs=5)

Epoch 1/5
1875/1875 [==============================] - 5s 3ms/step - loss: 0.5090 - accuracy: 0.8180
Epoch 2/5
1875/1875 [==============================] - 5s 3ms/step - loss: 0.3801 - accuracy: 0.8636
Epoch 3/5
1875/1875 [==============================] - 5s 3ms/step - loss: 0.3477 - accuracy: 0.8753
Epoch 4/5
1875/1875 [==============================] - 5s 3ms/step - loss: 0.3317 - accuracy: 0.8828
Epoch 5/5
1875/1875 [==============================] - 5s 3ms/step - loss: 0.3202 - accuracy: 0.8880


In [155]:
model.summary()

Model: "sequential_12"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 flatten_2 (Flatten)         (None, 784)               0         
                                                                 
 dense_22 (Dense)            (None, 100)               78500     
                                                                 
 LAST_DENSE (Dense)          (None, 10)                1010      
                                                                 
Total params: 79,510
Trainable params: 79,510
Non-trainable params: 0
_________________________________________________________________


In [156]:
##정확도
score = model.evaluate(test_scaled,test_label)
score

313/313 [==============================] - 1s 2ms/step - loss: 0.4016 - accuracy: 0.8701


[0.4016493260860443, 0.8701000213623047]